#!/usr/bin/env python3
"""
Apply curated translations to src/messages/*.json.

This tool is idempotent: it only touches keys present in the catalog and
leaves everything else (and key ordering) untouched. Keys not in the
TRANSLATIONS map for a given language fall back to English at runtime via
the i18n loader, so this script can safely run after every translation
batch.

Run from the repo root: `python3 scripts/translate.py`.
"""

import collections
import json
import sys
from pathlib import Path

MESSAGES_DIR = Path(__file__).resolve().parent.parent / "src" / "messages"


def apply(lang: str, mapping: dict[str, str]) -> None:
    path = MESSAGES_DIR / f"{lang}.json"
    if not path.exists():
        print(f"skip {lang}: file missing", file=sys.stderr)
        return
    with path.open() as f:
        data = json.load(f, object_pairs_hook=collections.OrderedDict)
    updated = skipped = 0
    for k, v in mapping.items():
        if k not in data:
            skipped += 1
            continue
        if data[k] != v:
            data[k] = v
            updated += 1
    with path.open("w") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"{lang}: {updated} keys updated ({skipped} unknown keys skipped)")


# ---------------------------------------------------------------------------
# Spanish — full coverage
# ---------------------------------------------------------------------------

ES = {
    # Misc small keys
    "nav.mempool": "Mempool",
    "header.github": "GitHub",
    "common.bytes": "bytes",
    "common.error": "Error",
    "common.hash": "Hash",
    "blocks.error": "Error",
    "blocks.txCount": "{count} tx",
    "blocksTable.hash": "Hash",
    "block.bytes": "bytes",
    "block.nonce": "Nonce",
    "block.bits": "Bits",
    "tx.bytes": "bytes",
    "tx.coinbaseTitle": "Coinbase",
    "address.conf": "{count} conf",
    "stats.stakingTab": "Staking",
    "stats.hash": "Hash",
    "stats.premium": "Premium",
    "stats.mempool": "Mempool",
    "mempool.title": "Mempool",
    "mempool.bytesValue": "{bytes} bytes",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "Mempool",
    "home.githubTitle": "GitHub",
    "home.networkMasternodes": "Masternodes",
    "home.statMasternodes": "Masternodes",
    "home.statMempool": "Mempool",
    "home.supplyHalvingsLabel": "Halvings",
    "home.txCount": "{count} tx",

    # masternodes
    "masternodes.header.title": "Masternodes",
    "masternodes.loadingMasternodes": "Cargando masternodes...",
    "masternodes.budget.description": "La gobernanza descentralizada de FairCoin permite a los propietarios de masternodes votar propuestas de presupuesto",
    "masternodes.budget.sections.budgetCommands": "Comandos de presupuesto",
    "masternodes.budget.sections.budgetStages": "Fases del presupuesto",
    "masternodes.budget.sections.example": "Ejemplo:",
    "masternodes.budget.sections.important": "Importante",
    "masternodes.budget.sections.output": "Salida:",
    "masternodes.budget.sections.warning": "Aviso",
    "masternodes.budget.alerts.collateralWarning": "Enviar una propuesta de presupuesto requiere una comisión de 5 FAIR que se quema. Asegúrate de que tu propuesta esté bien pensada antes de enviarla.",
    "masternodes.budget.alerts.votingRequirement": "Solo los propietarios de masternodes pueden votar propuestas. Asegúrate de que tu masternode esté en ENABLED antes de votar.",
    "masternodes.budget.stages.prepare.details": "Define el nombre de la propuesta, la URL, la dirección de pago, el importe y el número de ciclos de pago.",
    "masternodes.budget.stages.submit.details": "Envía la propuesta preparada a la red usando el hash de preparación. Cuesta 5 FAIR.",
    "masternodes.budget.stages.voting.details": "Los propietarios de masternodes pueden votar sí, no o abstenerse durante el periodo de votación.",
    "masternodes.budget.stages.finalization.details": "Al final del periodo de votación se cuentan los votos. La propuesta necesita más síes que noes.",
    "masternodes.budget.stages.budgetVoting.details": "Las propuestas aprobadas se incluyen en el siguiente ciclo presupuestario para su pago.",
    "masternodes.budget.stages.payment.details": "Los presupuestos aprobados reciben pagos desde la asignación de presupuesto de la blockchain.",
    "masternodes.budget.commands.prepare.name": "mnbudget prepare",
    "masternodes.budget.commands.prepare.description": "Prepara una propuesta de presupuesto para su envío",
    "masternodes.budget.commands.prepare.example": "mnbudget prepare nombre-propuesta http://url 10 720 dirección-pago 100",
    "masternodes.budget.commands.prepare.output": "Hash de preparación (64 caracteres hex)",
    "masternodes.budget.commands.prepare.copy": "Copiar comando",
    "masternodes.budget.commands.submit.name": "mnbudget submit",
    "masternodes.budget.commands.submit.description": "Envía una propuesta de presupuesto ya preparada",
    "masternodes.budget.commands.submit.example": "mnbudget submit nombre-propuesta http://url 10 720 dirección-pago 100 hash-preparación",
    "masternodes.budget.commands.submit.output": "Hash del presupuesto (64 caracteres hex)",
    "masternodes.budget.commands.submit.copy": "Copiar comando",
    "masternodes.budget.commands.vote.name": "mnbudget vote",
    "masternodes.budget.commands.vote.description": "Vota una propuesta de presupuesto",
    "masternodes.budget.commands.vote.example": "mnbudget vote hash-propuesta yes",
    "masternodes.budget.commands.vote.output": "Voto registrado correctamente",
    "masternodes.budget.commands.vote.copy": "Copiar comando",
    "masternodes.budget.commands.getinfo.name": "mnbudget getinfo",
    "masternodes.budget.commands.getinfo.description": "Obtén información de una propuesta concreta",
    "masternodes.budget.commands.getinfo.example": "mnbudget getinfo nombre-propuesta",
    "masternodes.budget.commands.getinfo.output": "Detalles de la propuesta incluyendo votos",
    "masternodes.budget.commands.getinfo.copy": "Copiar comando",
    "masternodes.budget.commands.projection.name": "mnbudget projection",
    "masternodes.budget.commands.projection.description": "Muestra la proyección de asignación del presupuesto",
    "masternodes.budget.commands.projection.example": "mnbudget projection",
    "masternodes.budget.commands.projection.output": "Lista de propuestas que se espera que reciban pago",
    "masternodes.budget.commands.projection.copy": "Copiar comando",
    "masternodes.budget.commands.finalbudget.name": "mnfinalbudget show",
    "masternodes.budget.commands.finalbudget.description": "Muestra los detalles del presupuesto finalizado",
    "masternodes.budget.commands.finalbudget.example": "mnfinalbudget show",
    "masternodes.budget.commands.finalbudget.output": "Detalles del presupuesto finalizado actual",
    "masternodes.budget.commands.finalbudget.copy": "Copiar comando",
    "masternodes.guide.configuration.title": "Archivos de configuración",
    "masternodes.guide.configuration.faircoinConf.title": "faircoin.conf (VPS)",
    "masternodes.guide.configuration.faircoinConf.copy": "Copiar faircoin.conf",
    "masternodes.guide.configuration.masternodeConf.title": "masternode.conf (local)",
    "masternodes.guide.configuration.masternodeConf.copy": "Copiar masternode.conf",
    "masternodes.guide.configuration.notes.title": "Notas importantes:",
    "masternodes.guide.configuration.notes.note1": "Sustituye ANYTHINGHERE por tus propias credenciales seguras",
    "masternodes.guide.configuration.notes.note2": "Sustituye YOURIP por la dirección IP de tu VPS",
    "masternodes.guide.configuration.notes.note3": "Sustituye PRIVATEKEYREPLACETHIS por tu clave privada de masternode",
    "masternodes.guide.configuration.notes.note4": "Sustituye INSERTYOURTXID por el ID de la transacción del colateral",
    "masternodes.requirements.hardware.title": "Hardware",
    "masternodes.requirements.hardware.items.0": "Mínimo 1 núcleo de CPU (recomendados 2 o más)",
    "masternodes.requirements.hardware.items.1": "Mínimo 2 GB de RAM (recomendados 4 GB)",
    "masternodes.requirements.hardware.items.2": "Mínimo 20 GB de almacenamiento SSD",
    "masternodes.requirements.hardware.items.3": "Conexión a internet estable",
    "masternodes.requirements.software.title": "Software",
    "masternodes.requirements.software.items.0": "Ubuntu 20.04 LTS o superior (recomendado)",
    "masternodes.requirements.software.items.1": "Cartera FairCoin Core (última versión)",
    "masternodes.requirements.software.items.2": "Cliente SSH para gestión remota",
    "masternodes.requirements.software.items.3": "Conocimientos básicos de línea de comandos Linux",
    "masternodes.requirements.network.title": "Red",
    "masternodes.requirements.network.items.0": "Dirección IP estática obligatoria",
    "masternodes.requirements.network.items.1": "Puerto 46372 abierto para mainnet",
    "masternodes.requirements.network.items.2": "Funcionamiento 24/7 recomendado",
    "masternodes.requirements.network.items.3": "5.000 FAIR de colateral en la cartera",
    "masternodes.requirements.note": "Estos son los requisitos mínimos. Para un mejor rendimiento, usa un VPS de un proveedor reputado con especificaciones más altas.",
    "masternodes.troubleshooting.help.title": "¿Necesitas más ayuda?",
    "masternodes.troubleshooting.help.description": "Únete a los canales de la comunidad FairCoin para recibir ayuda de otros operadores de masternode y del equipo de desarrollo.",
    "masternodes.troubleshooting.issues.0.issue": "El masternode no aparece como ENABLED",
    "masternodes.troubleshooting.issues.0.solution": "Espera al menos 15 confirmaciones tras enviar el colateral. Asegúrate de que tu VPS está sincronizado por completo y que faircoin.conf está bien configurado. Prueba a reiniciar el masternode desde tu cartera.",
    "masternodes.troubleshooting.issues.1.issue": "Errores de conexión rechazada o timeout",
    "masternodes.troubleshooting.issues.1.solution": "Comprueba que el puerto 46372 está abierto en el firewall del VPS. Verifica que la IP externa de la configuración coincide con la del VPS. Comprueba que el demonio FairCoin está corriendo.",
    "masternodes.troubleshooting.issues.2.issue": "El masternode pasa a NEW_START_REQUIRED",
    "masternodes.troubleshooting.issues.2.solution": "Suele significar que el VPS quedó offline o el demonio se cayó. Reinicia el demonio FairCoin en el VPS y luego reinicia el masternode desde tu cartera.",
    "masternodes.troubleshooting.issues.3.issue": "No se encuentra la transacción del colateral",
    "masternodes.troubleshooting.issues.3.solution": "Asegúrate de haber enviado exactamente 5.000 FAIR en una sola transacción. La transacción necesita al menos 15 confirmaciones. Comprueba 'masternode outputs' en la consola de depuración.",

    # search
    "search.title": "Búsqueda avanzada",
    "search.subtitle": "Busca bloques, transacciones y direcciones en la blockchain de FairCoin",
    "search.loading": "Cargando búsqueda...",
    "search.searching": "Buscando...",
    "search.searchButton": "Buscar",
    "search.placeholder": "Introduce altura de bloque, hash, ID de transacción o dirección...",
    "search.searchError": "Error de búsqueda",
    "search.searchTips": "Consejos de búsqueda:",
    "search.searchTipsTitle": "Consejos de búsqueda",
    "search.searchExamplesTab": "Ejemplos de búsqueda",
    "search.recentSearches": "Búsquedas recientes",
    "search.recentSearchesTab": "Búsquedas recientes",
    "search.noRecentSearches": "No hay búsquedas recientes",
    "search.clearHistory": "Borrar historial",
    "search.searchHistoryHint": "Tu historial de búsqueda aparecerá aquí",
    "search.quickActionsTab": "Acciones rápidas",
    "search.rawResults": "Resultados sin formato",
    "search.searchResults": "Resultados",
    "search.noResultsTitle": "Sin resultados",
    "search.noResultsFor": 'Sin resultados para "{query}"',
    "search.noResultsDescription": "No encontramos ningún bloque, transacción o dirección que coincida con tu búsqueda.",
    "search.commonIssues": "Problemas habituales:",
    "search.issueNotExist": "El elemento puede no existir en la red {network}",
    "search.issueSyncing": "La blockchain puede estar todavía sincronizándose",
    "search.issueTryDifferent": "Prueba a buscar otro término",
    "search.issueTypo": "Puede haber una errata en tu búsqueda",
    "search.tryAnotherSearch": "Probar otra búsqueda",
    "search.viewRecentBlocks": "Ver bloques recientes",
    "search.viewNetworkStats": "Ver estadísticas de red",
    "search.viewMasternodesInfo": "Ver información de masternodes",
    "search.browseRecentBlocks": "Explorar bloques recientes",
    "search.latestBlocks": "Últimos bloques",
    "search.networkStats": "Estadísticas de red",
    "search.masternodesTitle": "Masternodes",
    "search.query": "Consulta",
    "search.typeLabel": "Tipo",
    "search.networkLabel": "Red",
    "search.networkAwareness": "Conciencia de red",
    "search.tipCurrentNetwork": "Red actual: {network}",
    "search.tipNetwork": "Red: asegúrate de buscar en la red correcta ({network})",
    "search.tipQuickAccess": "Acceso rápido: usa la barra lateral para navegar",
    "search.tipSeparateIndices": "Índices separados: cada red tiene sus propios datos",
    "search.tipSwitchNetworks": "Cambiar de red: usa el selector de red",
    "search.tipCaseInsensitive": "Sin distinción de mayúsculas: todas las búsquedas ignoran mayúsculas/minúsculas",
    "search.tipBlockHeight": "Altura de bloque: introduce un número (p. ej. 680000)",
    "search.tipBlockHash": "Hash de bloque: introduce los 64 caracteres completos",
    "search.tipTransactionId": "ID de transacción: introduce los 64 caracteres completos",
    "search.tipAddress": "Dirección: introduce una dirección FairCoin válida",
    "search.tipAddresses": "Direcciones: las direcciones FairCoin comienzan por f, m, n o 2",
    "search.tipNumbers": "Números: alturas de bloque (p. ej. 680000)",
    "search.tip64Chars": "64 caracteres: hashes de bloque o IDs de transacción",
    "search.formatRecognition": "Reconocimiento de formato",
    "search.partialHash": "Hash parcial detectado",
    "search.partialHashDescription": "Has introducido un hash parcial. Completa los 64 caracteres para obtener resultados precisos.",
    "search.partialHashSuggestion": "Hash parcial",
    "search.completeHashHint": "Completa el hash para buscar",
    "search.lengthIndicator": "Longitud: {length}/64 caracteres",
    "search.blockHashLabel": "Hash de bloque",
    "search.blockHash": "Hash de bloque",
    "search.blockHashDescription": "Hash de bloque completo de 64 caracteres",
    "search.blockHashSuggestion": "Hash de bloque",
    "search.blockHeightLabel": "Altura de bloque",
    "search.blockHeightTitle": "Altura de bloque",
    "search.blockHeightDescription": "Altura numérica del bloque",
    "search.blockHeightSuggestion": "Altura de bloque {height}",
    "search.transactionIdLabel": "ID de transacción",
    "search.transactionIdTitle": "ID de transacción",
    "search.transactionIdDescription": "Hash de transacción completo de 64 caracteres",
    "search.transactionIdSuggestion": "ID de transacción",
    "search.addressLabel": "Dirección",
    "search.addressTitle": "Dirección",
    "search.addressDescription": "Dirección FairCoin",
    "search.fairCoinAddress": "Dirección FairCoin",
    "search.blockFound": "Bloque encontrado",
    "search.transactionFound": "Transacción encontrada",
    "search.addressFound": "Dirección encontrada",
    "search.balanceLabel": "Saldo",
    "search.totalReceivedLabel": "Total recibido",
    "search.totalSentLabel": "Total enviado",
    "search.transactionCountLabel": "Número de transacciones",
    "search.transactionsLabel": "Transacciones",
    "search.confirmationsLabel": "Confirmaciones",
    "search.difficultyLabel": "Dificultad",
    "search.inputsLabel": "Entradas",
    "search.outputsLabel": "Salidas",
    "search.timestampLabel": "Marca de tiempo",
    "search.sizeLabel": "Tamaño",
    "search.copyHash": "Copiar hash",
    "search.copyTxid": "Copiar TXID",
    "search.copyAddress": "Copiar dirección",
    "search.viewFullBlock": "Ver bloque completo",
    "search.viewFullTransaction": "Ver transacción completa",
    "search.viewFullAddress": "Ver dirección completa",
    "search.viewBlockAtHeight": "Ver bloque en la altura {height}",
    "search.viewBlockDetails": "Ver detalles del bloque",
    "search.viewTransactionDetails": "Ver detalles de la transacción",
    "search.viewAddressDetails": "Ver detalles y transacciones de la dirección",

    # tools
    "tools.feeCalculator.feeEstimate": "Estimación de comisión",
    "tools.feeCalculator.feeInformation": "Información de la comisión",
    "tools.feeCalculator.estimatedFee": "Comisión estimada",
    "tools.feeCalculator.totalCost": "Coste total",
    "tools.feeCalculator.amount": "Importe",
    "tools.feeCalculator.amountPlaceholder": "Introduce un importe en FAIR",
    "tools.feeCalculator.estimatedSize": "Tamaño estimado de la transacción: ~{bytes} bytes",
    "tools.feeCalculator.transactionDetails": "Detalles de la transacción",
    "tools.feeCalculator.currentNetwork": "Red actual",
    "tools.feeCalculator.blockTime": "Tiempo de bloque",
    "tools.feeCalculator.blockTimeValue": "~120 segundos",
    "tools.feeCalculator.confirmationTime": "Tiempo de confirmación",
    "tools.feeCalculator.recommendedConfirmations": "Confirmaciones recomendadas",
    "tools.feeCalculator.sixConfirmations": "6 confirmaciones para importes grandes",
    "tools.feeCalculator.feePriority": "Prioridad de la comisión",
    "tools.feeCalculator.lowPriority": "Prioridad baja",
    "tools.feeCalculator.lowPriorityDescription": "Puede tardar más en confirmar, comisión más baja",
    "tools.feeCalculator.standardPriority": "Prioridad estándar",
    "tools.feeCalculator.standardPriorityDescription": "Tiempo de confirmación normal, opción recomendada",
    "tools.feeCalculator.highPriority": "Prioridad alta",
    "tools.feeCalculator.highPriorityDescription": "Confirmación más rápida, comisión más alta",
    "tools.feeCalculator.instantX": "InstantX (prioridad)",
    "tools.feeCalculator.instantXLabel": "InstantSend",
    "tools.feeCalculator.instantXDescription": "Confirmación casi instantánea usando InstantSend",
    "tools.feeCalculator.privateSendLabel": "PrivateSend",
    "tools.feeCalculator.enhancedPrivacy": "Privacidad mejorada (mezcla de monedas)",
    "tools.feeCalculator.available": "Disponible (comisión más alta)",
    "tools.feeCalculator.standardMinimum": "Mínimo 0,0001 FAIR por KB",
    "tools.feeCalculator.standardTransactions": "Transacciones estándar",
    "tools.feeCalculator.nearInstantConfirmation": "Confirmación casi instantánea (requiere masternodes)",
    "tools.feeCalculator.multiSigSupport": "Multifirma",
    "tools.feeCalculator.variesByPriority": "Varía según el nivel de prioridad",
    "tools.feeCalculator.feeCalculationBased": "Comisión calculada según prioridad {priority}",
    "tools.feeCalculator.enterAmountTitle": "Introduce un importe",
    "tools.feeCalculator.enterAmountDescription": "Introduce un importe en FAIR para calcular la comisión estimada",
    "tools.feeCalculator.actualFeesDisclaimer": "Las comisiones reales pueden variar según la complejidad de la transacción",
    "tools.addressValidator.form.label": "Dirección FairCoin",
    "tools.addressValidator.form.placeholder": "Introduce una dirección FairCoin para validar",
    "tools.addressValidator.form.validate": "Validar",
    "tools.addressValidator.form.validating": "Validando...",
    "tools.addressValidator.validateSection.title": "Validar dirección",
    "tools.addressValidator.results.valid": "Dirección válida",
    "tools.addressValidator.results.invalid": "Dirección no válida",
    "tools.addressValidator.results.addressType": "Tipo de dirección",
    "tools.addressValidator.results.network": "Red",
    "tools.addressValidator.errors.title": "Error de validación",
    "tools.addressValidator.errors.empty": "Introduce una dirección para validar",
    "tools.addressValidator.errors.invalidLength": "Longitud de dirección no válida (debe tener 25-62 caracteres)",
    "tools.addressValidator.errors.invalidCharacters": "La dirección contiene caracteres no válidos (no Base58)",
    "tools.addressValidator.errors.unknownFormat": "Formato de dirección desconocido",
    "tools.addressValidator.addressTypes.p2pkh": "P2PKH (Pay-to-Public-Key-Hash)",
    "tools.addressValidator.addressTypes.p2pkhTestnet": "P2PKH Testnet",
    "tools.addressValidator.addressTypes.p2sh": "P2SH (Pay-to-Script-Hash)",
    "tools.addressValidator.addressTypes.p2shTestnet": "P2SH Testnet",
    "tools.addressValidator.addressDescriptions.p2pkh": "Dirección estándar de mainnet para recibir pagos",
    "tools.addressValidator.addressDescriptions.p2pkhTestnet": "Dirección estándar de testnet para pruebas",
    "tools.addressValidator.addressDescriptions.p2sh": "Dirección multifirma o basada en script en mainnet",
    "tools.addressValidator.addressDescriptions.p2shTestnet": "Dirección multifirma o basada en script en testnet",
    "tools.addressValidator.addressDescriptions.unknown": "Tipo de dirección desconocido",
    "tools.addressValidator.addressInfo.title": "Formatos de dirección FairCoin",
    "tools.addressValidator.addressInfo.mainnetP2PKH": "Mainnet P2PKH",
    "tools.addressValidator.addressInfo.mainnetP2PKHExample": "Empieza por 'f'",
    "tools.addressValidator.addressInfo.mainnetP2SH": "Mainnet P2SH",
    "tools.addressValidator.addressInfo.mainnetP2SHExample": "Empieza por 'F'",
    "tools.addressValidator.addressInfo.mainnetLength": "Longitud en mainnet",
    "tools.addressValidator.addressInfo.mainnetLengthValue": "25-34 caracteres",
    "tools.addressValidator.addressInfo.mainnetUsage": "Uso en mainnet",
    "tools.addressValidator.addressInfo.mainnetUsageValue": "Transacciones reales",
    "tools.addressValidator.addressInfo.testnetP2PKH": "Testnet P2PKH",
    "tools.addressValidator.addressInfo.testnetP2PKHValue": "Empieza por 'm' o 'n'",
    "tools.addressValidator.addressInfo.testnetP2SH": "Testnet P2SH",
    "tools.addressValidator.addressInfo.testnetP2SHValue": "Empieza por '2'",
    "tools.addressValidator.addressInfo.testnetLength": "Longitud en testnet",
    "tools.addressValidator.addressInfo.testnetLengthValue": "25-34 caracteres",
    "tools.addressValidator.addressInfo.testnetUsage": "Uso en testnet",
    "tools.addressValidator.addressInfo.testnetUsageValue": "Solo para pruebas",
    "tools.addressValidator.networkValidation.title": "Resultado de validación en red",
    "tools.addressValidator.networkValidation.valid": "Válida en la red",
    "tools.addressValidator.networkValidation.isMine": "Es mía",
    "tools.addressValidator.networkValidation.watchOnly": "Solo lectura",
    "tools.addressValidator.networkValidation.scriptAddress": "Dirección de script",
    "tools.addressValidator.warnings.networkMismatch.title": "Red no coincide",
    "tools.addressValidator.warnings.networkMismatch.description": "Esta dirección pertenece a {addressNetwork} pero te encuentras en {currentNetwork}",
}


# ---------------------------------------------------------------------------
# High-visibility namespaces translated for FR / DE / JA / KO / ZH / RU.
# Only nav, header, common, home, blocks, tx, address, txIndex, notFound,
# pwa, sidebar, language and the small misc keys end-users see most often.
# Other namespaces fall back to English at runtime.
# ---------------------------------------------------------------------------

FR_HIGH_VIS = {
    "nav.mempool": "Mempool",
    "header.github": "GitHub",
    "header.toggleTheme": "Changer de thème",
    "header.searchPlaceholder": "Rechercher des blocs, transactions, adresses...",
    "header.searchBlockchain": "Rechercher dans la blockchain",
    "header.searching": "Recherche...",
    "header.noResults": 'Aucun résultat pour "{query}"',
    "header.noResultsFound": "Aucun résultat",
    "header.searchFor": 'Rechercher "{query}"',
    "header.buyFair": "Acheter FAIR",
    "header.resources": "Ressources",
    "common.bytes": "octets",
    "common.error": "Erreur",
    "common.hash": "Hash",
    "common.refresh": "Actualiser",
    "common.tryAgain": "Réessayer",
    "common.previous": "Précédent",
    "common.next": "Suivant",
    "common.loading": "Chargement...",
    "common.yes": "Oui",
    "common.no": "Non",
    "common.fee": "Frais",
    "common.size": "Taille",
    "blocks.error": "Erreur",
    "blocks.txCount": "{count} tx",
    "blocksTable.hash": "Hash",
    "block.bytes": "octets",
    "block.nonce": "Nonce",
    "block.bits": "Bits",
    "tx.bytes": "octets",
    "tx.coinbaseTitle": "Coinbase",
    "address.conf": "{count} conf",
    "stats.mempool": "Mempool",
    "mempool.title": "Mempool",
    "mempool.bytesValue": "{bytes} octets",
    "mempool.feeRateValue": "{rate} sat/vO",
    "mempool.satValue": "{value} sat",
    "network.mempool": "Mempool",
    "home.statMasternodes": "Masternodes",
    "home.statMempool": "Mempool",
    "home.supplyHalvingsLabel": "Halvings",
    "home.txCount": "{count} tx",
    "home.networkMasternodes": "Masternodes",
    "home.githubTitle": "GitHub",
}

DE_HIGH_VIS = {
    "nav.mempool": "Mempool",
    "header.github": "GitHub",
    "header.toggleTheme": "Design umschalten",
    "header.searchPlaceholder": "Blöcke, Transaktionen, Adressen suchen...",
    "header.searchBlockchain": "Blockchain durchsuchen",
    "header.searching": "Suche läuft...",
    "header.noResults": 'Keine Ergebnisse für "{query}"',
    "header.noResultsFound": "Keine Ergebnisse gefunden",
    "header.searchFor": 'Nach "{query}" suchen',
    "header.buyFair": "FAIR kaufen",
    "header.resources": "Ressourcen",
    "common.bytes": "Bytes",
    "common.error": "Fehler",
    "common.hash": "Hash",
    "common.refresh": "Aktualisieren",
    "common.tryAgain": "Erneut versuchen",
    "common.previous": "Zurück",
    "common.next": "Weiter",
    "common.loading": "Lädt...",
    "common.yes": "Ja",
    "common.no": "Nein",
    "common.fee": "Gebühr",
    "common.size": "Größe",
    "blocks.error": "Fehler",
    "blocks.txCount": "{count} Tx",
    "blocksTable.hash": "Hash",
    "block.bytes": "Bytes",
    "block.nonce": "Nonce",
    "block.bits": "Bits",
    "tx.bytes": "Bytes",
    "tx.coinbaseTitle": "Coinbase",
    "address.conf": "{count} Best.",
    "stats.mempool": "Mempool",
    "mempool.title": "Mempool",
    "mempool.bytesValue": "{bytes} Bytes",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "Mempool",
    "home.statMasternodes": "Masternodes",
    "home.statMempool": "Mempool",
    "home.supplyHalvingsLabel": "Halvings",
    "home.txCount": "{count} Tx",
    "home.networkMasternodes": "Masternodes",
    "home.githubTitle": "GitHub",
}

JA_HIGH_VIS = {
    "nav.mempool": "メンプール",
    "header.github": "GitHub",
    "header.toggleTheme": "テーマを切り替え",
    "header.searchPlaceholder": "ブロック、トランザクション、アドレスを検索...",
    "header.searchBlockchain": "ブロックチェーンを検索",
    "header.searching": "検索中...",
    "header.noResults": '"{query}" の結果なし',
    "header.noResultsFound": "結果が見つかりません",
    "header.searchFor": '"{query}" を検索',
    "header.buyFair": "FAIR を購入",
    "header.resources": "リソース",
    "common.bytes": "バイト",
    "common.error": "エラー",
    "common.hash": "ハッシュ",
    "common.refresh": "更新",
    "common.tryAgain": "再試行",
    "common.previous": "前へ",
    "common.next": "次へ",
    "common.loading": "読み込み中...",
    "common.yes": "はい",
    "common.no": "いいえ",
    "common.fee": "手数料",
    "common.size": "サイズ",
    "blocks.error": "エラー",
    "blocks.txCount": "{count} tx",
    "blocksTable.hash": "ハッシュ",
    "block.bytes": "バイト",
    "block.nonce": "Nonce",
    "block.bits": "Bits",
    "tx.bytes": "バイト",
    "tx.coinbaseTitle": "コインベース",
    "address.conf": "{count} 確認",
    "stats.mempool": "メンプール",
    "mempool.title": "メンプール",
    "mempool.bytesValue": "{bytes} バイト",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "メンプール",
    "home.statMasternodes": "マスターノード",
    "home.statMempool": "メンプール",
    "home.networkMasternodes": "マスターノード",
    "home.githubTitle": "GitHub",
}

KO_HIGH_VIS = {
    "nav.mempool": "Mempool",
    "header.github": "GitHub",
    "header.toggleTheme": "테마 전환",
    "header.searchPlaceholder": "블록, 트랜잭션, 주소 검색...",
    "header.searchBlockchain": "블록체인 검색",
    "header.searching": "검색 중...",
    "header.noResults": '"{query}"에 대한 결과 없음',
    "header.noResultsFound": "결과를 찾을 수 없습니다",
    "header.searchFor": '"{query}" 검색',
    "header.buyFair": "FAIR 구매",
    "header.resources": "리소스",
    "common.bytes": "바이트",
    "common.error": "오류",
    "common.hash": "해시",
    "common.refresh": "새로 고침",
    "common.tryAgain": "다시 시도",
    "common.previous": "이전",
    "common.next": "다음",
    "common.loading": "로딩 중...",
    "common.yes": "예",
    "common.no": "아니오",
    "common.fee": "수수료",
    "common.size": "크기",
    "blocks.error": "오류",
    "blocks.txCount": "{count} tx",
    "blocksTable.hash": "해시",
    "block.bytes": "바이트",
    "tx.bytes": "바이트",
    "tx.coinbaseTitle": "코인베이스",
    "address.conf": "{count} 확인",
    "stats.mempool": "Mempool",
    "mempool.title": "Mempool",
    "mempool.bytesValue": "{bytes} 바이트",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "Mempool",
    "home.statMasternodes": "마스터노드",
    "home.statMempool": "Mempool",
    "home.networkMasternodes": "마스터노드",
    "home.githubTitle": "GitHub",
}

ZH_HIGH_VIS = {
    "nav.mempool": "内存池",
    "header.github": "GitHub",
    "header.toggleTheme": "切换主题",
    "header.searchPlaceholder": "搜索区块、交易、地址...",
    "header.searchBlockchain": "搜索区块链",
    "header.searching": "搜索中...",
    "header.noResults": '没有找到"{query}"的结果',
    "header.noResultsFound": "未找到结果",
    "header.searchFor": '搜索"{query}"',
    "header.buyFair": "购买 FAIR",
    "header.resources": "资源",
    "common.bytes": "字节",
    "common.error": "错误",
    "common.hash": "哈希",
    "common.refresh": "刷新",
    "common.tryAgain": "重试",
    "common.previous": "上一页",
    "common.next": "下一页",
    "common.loading": "加载中...",
    "common.yes": "是",
    "common.no": "否",
    "common.fee": "手续费",
    "common.size": "大小",
    "blocks.error": "错误",
    "blocks.txCount": "{count} 笔",
    "blocksTable.hash": "哈希",
    "block.bytes": "字节",
    "tx.bytes": "字节",
    "tx.coinbaseTitle": "Coinbase",
    "address.conf": "{count} 次确认",
    "stats.mempool": "内存池",
    "mempool.title": "内存池",
    "mempool.bytesValue": "{bytes} 字节",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "内存池",
    "home.statMasternodes": "主节点",
    "home.statMempool": "内存池",
    "home.networkMasternodes": "主节点",
    "home.githubTitle": "GitHub",
}

RU_HIGH_VIS = {
    "nav.mempool": "Мемпул",
    "header.github": "GitHub",
    "header.toggleTheme": "Переключить тему",
    "header.searchPlaceholder": "Поиск блоков, транзакций, адресов...",
    "header.searchBlockchain": "Поиск в блокчейне",
    "header.searching": "Поиск...",
    "header.noResults": 'Нет результатов для "{query}"',
    "header.noResultsFound": "Результаты не найдены",
    "header.searchFor": 'Найти "{query}"',
    "header.buyFair": "Купить FAIR",
    "header.resources": "Ресурсы",
    "common.bytes": "байт",
    "common.error": "Ошибка",
    "common.hash": "Хеш",
    "common.refresh": "Обновить",
    "common.tryAgain": "Повторить",
    "common.previous": "Назад",
    "common.next": "Далее",
    "common.loading": "Загрузка...",
    "common.yes": "Да",
    "common.no": "Нет",
    "common.fee": "Комиссия",
    "common.size": "Размер",
    "blocks.error": "Ошибка",
    "blocks.txCount": "{count} тх",
    "blocksTable.hash": "Хеш",
    "block.bytes": "байт",
    "tx.bytes": "байт",
    "tx.coinbaseTitle": "Coinbase",
    "address.conf": "{count} подтв.",
    "stats.mempool": "Мемпул",
    "mempool.title": "Мемпул",
    "mempool.bytesValue": "{bytes} байт",
    "mempool.feeRateValue": "{rate} sat/vB",
    "mempool.satValue": "{value} sat",
    "network.mempool": "Мемпул",
    "home.statMasternodes": "Мастерноды",
    "home.statMempool": "Мемпул",
    "home.networkMasternodes": "Мастерноды",
    "home.githubTitle": "GitHub",
}


def main() -> None:
    apply("es", ES)
    apply("fr", FR_HIGH_VIS)
    apply("de", DE_HIGH_VIS)
    apply("ja", JA_HIGH_VIS)
    apply("ko", KO_HIGH_VIS)
    apply("zh", ZH_HIGH_VIS)
    apply("ru", RU_HIGH_VIS)


if __name__ == "__main__":
    main()
